name: Wiki-Sync

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Wiki-Sync
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    # GoPlantUML https://github.com/jfeliu007/goplantuml
    - name: Install GoPlantUML
      run: |
        go get github.com/jfeliu007/goplantuml/parser
        go get github.com/jfeliu007/goplantuml/cmd/goplantuml
        cd $GOPATH/src/github.com/jfeliu007/goplantuml
        go install ./...
      env:
        GOPATH: /home/runner/go
        GO111MODULE: off
    - name: Generate PUML
      run: goplantuml -recursive .\
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Generate SVG
      run: java -jar .\third_party\plantuml.jar .\output.puml -v

